# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cowait.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63owait.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n\x06Header\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12(\n\x04time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"7\n\x0bTaskInitReq\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x0f\n\x07version\x18\x02 \x01(\t\"\x0f\n\rTaskInitReply\"8\n\x0eTaskFailureReq\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x12\n\x10TaskFailureReply\":\n\x0fTaskCompleteReq\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x0e\n\x06result\x18\x02 \x01(\t\"\x13\n\x11TaskCompleteReply\"?\n\x08LogEntry\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"\x1d\n\nLogSummary\x12\x0f\n\x07records\x18\x01 \x01(\x03\x32\xc6\x01\n\x04Task\x12*\n\x08TaskInit\x12\x0c.TaskInitReq\x1a\x0e.TaskInitReply\"\x00\x12\x33\n\x0bTaskFailure\x12\x0f.TaskFailureReq\x1a\x11.TaskFailureReply\"\x00\x12\x36\n\x0cTaskComplete\x12\x10.TaskCompleteReq\x1a\x12.TaskCompleteReply\"\x00\x12%\n\x07TaskLog\x12\t.LogEntry\x1a\x0b.LogSummary\"\x00(\x01\x42\x10Z\x0e\x63owait/core/pbb\x06proto3')



_HEADER = DESCRIPTOR.message_types_by_name['Header']
_TASKINITREQ = DESCRIPTOR.message_types_by_name['TaskInitReq']
_TASKINITREPLY = DESCRIPTOR.message_types_by_name['TaskInitReply']
_TASKFAILUREREQ = DESCRIPTOR.message_types_by_name['TaskFailureReq']
_TASKFAILUREREPLY = DESCRIPTOR.message_types_by_name['TaskFailureReply']
_TASKCOMPLETEREQ = DESCRIPTOR.message_types_by_name['TaskCompleteReq']
_TASKCOMPLETEREPLY = DESCRIPTOR.message_types_by_name['TaskCompleteReply']
_LOGENTRY = DESCRIPTOR.message_types_by_name['LogEntry']
_LOGSUMMARY = DESCRIPTOR.message_types_by_name['LogSummary']
Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'cowait_pb2'
  # @@protoc_insertion_point(class_scope:Header)
  })
_sym_db.RegisterMessage(Header)

TaskInitReq = _reflection.GeneratedProtocolMessageType('TaskInitReq', (_message.Message,), {
  'DESCRIPTOR' : _TASKINITREQ,
  '__module__' : 'cowait_pb2'
  # @@protoc_insertion_point(class_scope:TaskInitReq)
  })
_sym_db.RegisterMessage(TaskInitReq)

TaskInitReply = _reflection.GeneratedProtocolMessageType('TaskInitReply', (_message.Message,), {
  'DESCRIPTOR' : _TASKINITREPLY,
  '__module__' : 'cowait_pb2'
  # @@protoc_insertion_point(class_scope:TaskInitReply)
  })
_sym_db.RegisterMessage(TaskInitReply)

TaskFailureReq = _reflection.GeneratedProtocolMessageType('TaskFailureReq', (_message.Message,), {
  'DESCRIPTOR' : _TASKFAILUREREQ,
  '__module__' : 'cowait_pb2'
  # @@protoc_insertion_point(class_scope:TaskFailureReq)
  })
_sym_db.RegisterMessage(TaskFailureReq)

TaskFailureReply = _reflection.GeneratedProtocolMessageType('TaskFailureReply', (_message.Message,), {
  'DESCRIPTOR' : _TASKFAILUREREPLY,
  '__module__' : 'cowait_pb2'
  # @@protoc_insertion_point(class_scope:TaskFailureReply)
  })
_sym_db.RegisterMessage(TaskFailureReply)

TaskCompleteReq = _reflection.GeneratedProtocolMessageType('TaskCompleteReq', (_message.Message,), {
  'DESCRIPTOR' : _TASKCOMPLETEREQ,
  '__module__' : 'cowait_pb2'
  # @@protoc_insertion_point(class_scope:TaskCompleteReq)
  })
_sym_db.RegisterMessage(TaskCompleteReq)

TaskCompleteReply = _reflection.GeneratedProtocolMessageType('TaskCompleteReply', (_message.Message,), {
  'DESCRIPTOR' : _TASKCOMPLETEREPLY,
  '__module__' : 'cowait_pb2'
  # @@protoc_insertion_point(class_scope:TaskCompleteReply)
  })
_sym_db.RegisterMessage(TaskCompleteReply)

LogEntry = _reflection.GeneratedProtocolMessageType('LogEntry', (_message.Message,), {
  'DESCRIPTOR' : _LOGENTRY,
  '__module__' : 'cowait_pb2'
  # @@protoc_insertion_point(class_scope:LogEntry)
  })
_sym_db.RegisterMessage(LogEntry)

LogSummary = _reflection.GeneratedProtocolMessageType('LogSummary', (_message.Message,), {
  'DESCRIPTOR' : _LOGSUMMARY,
  '__module__' : 'cowait_pb2'
  # @@protoc_insertion_point(class_scope:LogSummary)
  })
_sym_db.RegisterMessage(LogSummary)

_TASK = DESCRIPTOR.services_by_name['Task']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\016cowait/core/pb'
  _HEADER._serialized_start=49
  _HEADER._serialized_end=116
  _TASKINITREQ._serialized_start=118
  _TASKINITREQ._serialized_end=173
  _TASKINITREPLY._serialized_start=175
  _TASKINITREPLY._serialized_end=190
  _TASKFAILUREREQ._serialized_start=192
  _TASKFAILUREREQ._serialized_end=248
  _TASKFAILUREREPLY._serialized_start=250
  _TASKFAILUREREPLY._serialized_end=268
  _TASKCOMPLETEREQ._serialized_start=270
  _TASKCOMPLETEREQ._serialized_end=328
  _TASKCOMPLETEREPLY._serialized_start=330
  _TASKCOMPLETEREPLY._serialized_end=349
  _LOGENTRY._serialized_start=351
  _LOGENTRY._serialized_end=414
  _LOGSUMMARY._serialized_start=416
  _LOGSUMMARY._serialized_end=445
  _TASK._serialized_start=448
  _TASK._serialized_end=646
# @@protoc_insertion_point(module_scope)
