# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import cowait_pb2 as cowait__pb2


class ExecutorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TaskInit = channel.unary_unary(
                '/Executor/TaskInit',
                request_serializer=cowait__pb2.TaskInitReq.SerializeToString,
                response_deserializer=cowait__pb2.TaskInitReply.FromString,
                )
        self.TaskFailure = channel.unary_unary(
                '/Executor/TaskFailure',
                request_serializer=cowait__pb2.TaskFailureReq.SerializeToString,
                response_deserializer=cowait__pb2.TaskFailureReply.FromString,
                )
        self.TaskComplete = channel.unary_unary(
                '/Executor/TaskComplete',
                request_serializer=cowait__pb2.TaskCompleteReq.SerializeToString,
                response_deserializer=cowait__pb2.TaskCompleteReply.FromString,
                )
        self.TaskLog = channel.stream_unary(
                '/Executor/TaskLog',
                request_serializer=cowait__pb2.LogEntry.SerializeToString,
                response_deserializer=cowait__pb2.LogSummary.FromString,
                )


class ExecutorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TaskInit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskFailure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskLog(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TaskInit': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskInit,
                    request_deserializer=cowait__pb2.TaskInitReq.FromString,
                    response_serializer=cowait__pb2.TaskInitReply.SerializeToString,
            ),
            'TaskFailure': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskFailure,
                    request_deserializer=cowait__pb2.TaskFailureReq.FromString,
                    response_serializer=cowait__pb2.TaskFailureReply.SerializeToString,
            ),
            'TaskComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskComplete,
                    request_deserializer=cowait__pb2.TaskCompleteReq.FromString,
                    response_serializer=cowait__pb2.TaskCompleteReply.SerializeToString,
            ),
            'TaskLog': grpc.stream_unary_rpc_method_handler(
                    servicer.TaskLog,
                    request_deserializer=cowait__pb2.LogEntry.FromString,
                    response_serializer=cowait__pb2.LogSummary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Executor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Executor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TaskInit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Executor/TaskInit',
            cowait__pb2.TaskInitReq.SerializeToString,
            cowait__pb2.TaskInitReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TaskFailure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Executor/TaskFailure',
            cowait__pb2.TaskFailureReq.SerializeToString,
            cowait__pb2.TaskFailureReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TaskComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Executor/TaskComplete',
            cowait__pb2.TaskCompleteReq.SerializeToString,
            cowait__pb2.TaskCompleteReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TaskLog(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/Executor/TaskLog',
            cowait__pb2.LogEntry.SerializeToString,
            cowait__pb2.LogSummary.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class CowaitStub(object):
    """Api Service

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/Cowait/CreateTask',
                request_serializer=cowait__pb2.CreateTaskReq.SerializeToString,
                response_deserializer=cowait__pb2.CreateTaskReply.FromString,
                )
        self.QueryTasks = channel.unary_unary(
                '/Cowait/QueryTasks',
                request_serializer=cowait__pb2.QueryTasksReq.SerializeToString,
                response_deserializer=cowait__pb2.QueryTasksReply.FromString,
                )
        self.KillTask = channel.unary_unary(
                '/Cowait/KillTask',
                request_serializer=cowait__pb2.KillTaskReq.SerializeToString,
                response_deserializer=cowait__pb2.KillTaskReply.FromString,
                )
        self.AwaitTask = channel.unary_stream(
                '/Cowait/AwaitTask',
                request_serializer=cowait__pb2.AwaitTaskReq.SerializeToString,
                response_deserializer=cowait__pb2.AwaitTaskReply.FromString,
                )


class CowaitServicer(object):
    """Api Service

    """

    def CreateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KillTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AwaitTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CowaitServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=cowait__pb2.CreateTaskReq.FromString,
                    response_serializer=cowait__pb2.CreateTaskReply.SerializeToString,
            ),
            'QueryTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryTasks,
                    request_deserializer=cowait__pb2.QueryTasksReq.FromString,
                    response_serializer=cowait__pb2.QueryTasksReply.SerializeToString,
            ),
            'KillTask': grpc.unary_unary_rpc_method_handler(
                    servicer.KillTask,
                    request_deserializer=cowait__pb2.KillTaskReq.FromString,
                    response_serializer=cowait__pb2.KillTaskReply.SerializeToString,
            ),
            'AwaitTask': grpc.unary_stream_rpc_method_handler(
                    servicer.AwaitTask,
                    request_deserializer=cowait__pb2.AwaitTaskReq.FromString,
                    response_serializer=cowait__pb2.AwaitTaskReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Cowait', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Cowait(object):
    """Api Service

    """

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Cowait/CreateTask',
            cowait__pb2.CreateTaskReq.SerializeToString,
            cowait__pb2.CreateTaskReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Cowait/QueryTasks',
            cowait__pb2.QueryTasksReq.SerializeToString,
            cowait__pb2.QueryTasksReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def KillTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Cowait/KillTask',
            cowait__pb2.KillTaskReq.SerializeToString,
            cowait__pb2.KillTaskReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AwaitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Cowait/AwaitTask',
            cowait__pb2.AwaitTaskReq.SerializeToString,
            cowait__pb2.AwaitTaskReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ClusterStub(object):
    """
    Cluster Uplink


    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Info = channel.unary_unary(
                '/Cluster/Info',
                request_serializer=cowait__pb2.ClusterInfoReq.SerializeToString,
                response_deserializer=cowait__pb2.ClusterInfoReply.FromString,
                )
        self.Spawn = channel.unary_unary(
                '/Cluster/Spawn',
                request_serializer=cowait__pb2.ClusterSpawnReq.SerializeToString,
                response_deserializer=cowait__pb2.ClusterSpawnReply.FromString,
                )
        self.Kill = channel.unary_unary(
                '/Cluster/Kill',
                request_serializer=cowait__pb2.ClusterKillReq.SerializeToString,
                response_deserializer=cowait__pb2.ClusterKillReply.FromString,
                )
        self.Poke = channel.unary_unary(
                '/Cluster/Poke',
                request_serializer=cowait__pb2.ClusterPokeReq.SerializeToString,
                response_deserializer=cowait__pb2.ClusterPokeReply.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/Cluster/Subscribe',
                request_serializer=cowait__pb2.ClusterSubscribeReq.SerializeToString,
                response_deserializer=cowait__pb2.ClusterEvent.FromString,
                )


class ClusterServicer(object):
    """
    Cluster Uplink


    """

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Spawn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Kill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Poke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=cowait__pb2.ClusterInfoReq.FromString,
                    response_serializer=cowait__pb2.ClusterInfoReply.SerializeToString,
            ),
            'Spawn': grpc.unary_unary_rpc_method_handler(
                    servicer.Spawn,
                    request_deserializer=cowait__pb2.ClusterSpawnReq.FromString,
                    response_serializer=cowait__pb2.ClusterSpawnReply.SerializeToString,
            ),
            'Kill': grpc.unary_unary_rpc_method_handler(
                    servicer.Kill,
                    request_deserializer=cowait__pb2.ClusterKillReq.FromString,
                    response_serializer=cowait__pb2.ClusterKillReply.SerializeToString,
            ),
            'Poke': grpc.unary_unary_rpc_method_handler(
                    servicer.Poke,
                    request_deserializer=cowait__pb2.ClusterPokeReq.FromString,
                    response_serializer=cowait__pb2.ClusterPokeReply.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=cowait__pb2.ClusterSubscribeReq.FromString,
                    response_serializer=cowait__pb2.ClusterEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Cluster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Cluster(object):
    """
    Cluster Uplink


    """

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Cluster/Info',
            cowait__pb2.ClusterInfoReq.SerializeToString,
            cowait__pb2.ClusterInfoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Spawn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Cluster/Spawn',
            cowait__pb2.ClusterSpawnReq.SerializeToString,
            cowait__pb2.ClusterSpawnReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Kill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Cluster/Kill',
            cowait__pb2.ClusterKillReq.SerializeToString,
            cowait__pb2.ClusterKillReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Poke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Cluster/Poke',
            cowait__pb2.ClusterPokeReq.SerializeToString,
            cowait__pb2.ClusterPokeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Cluster/Subscribe',
            cowait__pb2.ClusterSubscribeReq.SerializeToString,
            cowait__pb2.ClusterEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
