version: '2'
networks:
  cowait:
    external: true
services:
  base:
    image: 'cowait/gowait'
    build: 
      context: '.'
      target: 'executor'

    # we never want to run the base image directly
    entrypoint: ['echo', '-- client disabled --']
    command: ''

  python:
    image: 'cowait/gowait-python'
    build: './sdk/cowait-python'
    depends_on:
      - 'base'

    # we never want to run the base image directly
    entrypoint: ['echo', '-- client disabled --']
    command: ''

  daemon:
    image: 'cowait/cowaitd'
    build: 
      context: '.'
      target: 'daemon'
    command: ['-driver=docker']
    networks:
      - 'default'
      - 'cowait'
    ports:
      - '1337:1337'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  cloud:
    image: 'cowait/cloud'
    build: 
      context: '.'
      target: 'cloud'
