version: '2'
services:
  base:
    image: 'cowait/gowait'
    build: 
      context: '.'
      target: 'executor'

    # we never want to run the base image directly
    entrypoint: ['echo', '-- client disabled --']
    command: ''

  python:
    image: 'cowait/gowait-python'
    build: './python'
    depends_on:
      - 'base'

    # we never want to run the base image directly
    entrypoint: ['echo', '-- client disabled --']
    command: ''

  daemon:
    image: 'cowait/cowaitd'
    build: 
      context: '.'
      target: 'daemon'

  cloud:
    image: 'cowait/cloud'
    build: 
      context: '.'
      target: 'cloud'
