// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: core/pb/cowait.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId  string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Time    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_pb_cowait_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_core_pb_cowait_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_core_pb_cowait_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Header) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Header) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type TaskInitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Taskdef *TaskDef `protobuf:"bytes,3,opt,name=taskdef,proto3" json:"taskdef,omitempty"`
}

func (x *TaskInitReq) Reset() {
	*x = TaskInitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_pb_cowait_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInitReq) ProtoMessage() {}

func (x *TaskInitReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_pb_cowait_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInitReq.ProtoReflect.Descriptor instead.
func (*TaskInitReq) Descriptor() ([]byte, []int) {
	return file_core_pb_cowait_proto_rawDescGZIP(), []int{1}
}

func (x *TaskInitReq) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TaskInitReq) GetTaskdef() *TaskDef {
	if x != nil {
		return x.Taskdef
	}
	return nil
}

type TaskInitReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TaskInitReply) Reset() {
	*x = TaskInitReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_pb_cowait_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInitReply) ProtoMessage() {}

func (x *TaskInitReply) ProtoReflect() protoreflect.Message {
	mi := &file_core_pb_cowait_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInitReply.ProtoReflect.Descriptor instead.
func (*TaskInitReply) Descriptor() ([]byte, []int) {
	return file_core_pb_cowait_proto_rawDescGZIP(), []int{2}
}

type TaskFailureReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Error  string  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *TaskFailureReq) Reset() {
	*x = TaskFailureReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_pb_cowait_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskFailureReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskFailureReq) ProtoMessage() {}

func (x *TaskFailureReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_pb_cowait_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskFailureReq.ProtoReflect.Descriptor instead.
func (*TaskFailureReq) Descriptor() ([]byte, []int) {
	return file_core_pb_cowait_proto_rawDescGZIP(), []int{3}
}

func (x *TaskFailureReq) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TaskFailureReq) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TaskFailureReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TaskFailureReply) Reset() {
	*x = TaskFailureReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_pb_cowait_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskFailureReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskFailureReply) ProtoMessage() {}

func (x *TaskFailureReply) ProtoReflect() protoreflect.Message {
	mi := &file_core_pb_cowait_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskFailureReply.ProtoReflect.Descriptor instead.
func (*TaskFailureReply) Descriptor() ([]byte, []int) {
	return file_core_pb_cowait_proto_rawDescGZIP(), []int{4}
}

type TaskCompleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Result string  `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *TaskCompleteReq) Reset() {
	*x = TaskCompleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_pb_cowait_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskCompleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompleteReq) ProtoMessage() {}

func (x *TaskCompleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_pb_cowait_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompleteReq.ProtoReflect.Descriptor instead.
func (*TaskCompleteReq) Descriptor() ([]byte, []int) {
	return file_core_pb_cowait_proto_rawDescGZIP(), []int{5}
}

func (x *TaskCompleteReq) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TaskCompleteReq) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type TaskCompleteReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TaskCompleteReply) Reset() {
	*x = TaskCompleteReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_pb_cowait_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskCompleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompleteReply) ProtoMessage() {}

func (x *TaskCompleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_core_pb_cowait_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompleteReply.ProtoReflect.Descriptor instead.
func (*TaskCompleteReply) Descriptor() ([]byte, []int) {
	return file_core_pb_cowait_proto_rawDescGZIP(), []int{6}
}

type TaskDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Parent    string   `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Name      string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Image     string   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Namespace string   `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Command   []string `protobuf:"bytes,6,rep,name=command,proto3" json:"command,omitempty"`
	Input     string   `protobuf:"bytes,7,opt,name=input,proto3" json:"input,omitempty"`
	Timeout   int64    `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *TaskDef) Reset() {
	*x = TaskDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_pb_cowait_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDef) ProtoMessage() {}

func (x *TaskDef) ProtoReflect() protoreflect.Message {
	mi := &file_core_pb_cowait_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDef.ProtoReflect.Descriptor instead.
func (*TaskDef) Descriptor() ([]byte, []int) {
	return file_core_pb_cowait_proto_rawDescGZIP(), []int{7}
}

func (x *TaskDef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskDef) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *TaskDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskDef) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *TaskDef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TaskDef) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *TaskDef) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *TaskDef) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	File   string  `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Data   string  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_pb_cowait_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_core_pb_cowait_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_core_pb_cowait_proto_rawDescGZIP(), []int{8}
}

func (x *LogEntry) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LogEntry) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *LogEntry) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type LogSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records int64 `protobuf:"varint,1,opt,name=records,proto3" json:"records,omitempty"`
}

func (x *LogSummary) Reset() {
	*x = LogSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_pb_cowait_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSummary) ProtoMessage() {}

func (x *LogSummary) ProtoReflect() protoreflect.Message {
	mi := &file_core_pb_cowait_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSummary.ProtoReflect.Descriptor instead.
func (*LogSummary) Descriptor() ([]byte, []int) {
	return file_core_pb_cowait_proto_rawDescGZIP(), []int{9}
}

func (x *LogSummary) GetRecords() int64 {
	if x != nil {
		return x.Records
	}
	return 0
}

var File_core_pb_cowait_proto protoreflect.FileDescriptor

var file_core_pb_cowait_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x77, 0x61, 0x69, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x22, 0x52, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x64, 0x65, 0x66, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x66, 0x52,
	0x07, 0x74, 0x61, 0x73, 0x6b, 0x64, 0x65, 0x66, 0x22, 0x0f, 0x0a, 0x0d, 0x54, 0x61, 0x73, 0x6b,
	0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x47, 0x0a, 0x0e, 0x54, 0x61, 0x73,
	0x6b, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x12, 0x0a, 0x10, 0x54, 0x61, 0x73, 0x6b, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x4a, 0x0a, 0x0f, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0xc3, 0x01, 0x0a, 0x07, 0x54, 0x61, 0x73, 0x6b,
	0x44, 0x65, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x53, 0x0a,
	0x08, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x26, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x32, 0xc6, 0x01, 0x0a, 0x04, 0x54,
	0x61, 0x73, 0x6b, 0x12, 0x2a, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x69, 0x74, 0x12,
	0x0c, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x33, 0x0a, 0x0b, 0x54, 0x61, 0x73, 0x6b, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x12, 0x0f,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x11, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0c, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x10, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x07,
	0x54, 0x61, 0x73, 0x6b, 0x4c, 0x6f, 0x67, 0x12, 0x09, 0x2e, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x1a, 0x0b, 0x2e, 0x4c, 0x6f, 0x67, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22,
	0x00, 0x28, 0x01, 0x42, 0x10, 0x5a, 0x0e, 0x63, 0x6f, 0x77, 0x61, 0x69, 0x74, 0x2f, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_pb_cowait_proto_rawDescOnce sync.Once
	file_core_pb_cowait_proto_rawDescData = file_core_pb_cowait_proto_rawDesc
)

func file_core_pb_cowait_proto_rawDescGZIP() []byte {
	file_core_pb_cowait_proto_rawDescOnce.Do(func() {
		file_core_pb_cowait_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_pb_cowait_proto_rawDescData)
	})
	return file_core_pb_cowait_proto_rawDescData
}

var file_core_pb_cowait_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_core_pb_cowait_proto_goTypes = []interface{}{
	(*Header)(nil),                // 0: Header
	(*TaskInitReq)(nil),           // 1: TaskInitReq
	(*TaskInitReply)(nil),         // 2: TaskInitReply
	(*TaskFailureReq)(nil),        // 3: TaskFailureReq
	(*TaskFailureReply)(nil),      // 4: TaskFailureReply
	(*TaskCompleteReq)(nil),       // 5: TaskCompleteReq
	(*TaskCompleteReply)(nil),     // 6: TaskCompleteReply
	(*TaskDef)(nil),               // 7: TaskDef
	(*LogEntry)(nil),              // 8: LogEntry
	(*LogSummary)(nil),            // 9: LogSummary
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_core_pb_cowait_proto_depIdxs = []int32{
	10, // 0: Header.time:type_name -> google.protobuf.Timestamp
	0,  // 1: TaskInitReq.header:type_name -> Header
	7,  // 2: TaskInitReq.taskdef:type_name -> TaskDef
	0,  // 3: TaskFailureReq.header:type_name -> Header
	0,  // 4: TaskCompleteReq.header:type_name -> Header
	0,  // 5: LogEntry.header:type_name -> Header
	1,  // 6: Task.TaskInit:input_type -> TaskInitReq
	3,  // 7: Task.TaskFailure:input_type -> TaskFailureReq
	5,  // 8: Task.TaskComplete:input_type -> TaskCompleteReq
	8,  // 9: Task.TaskLog:input_type -> LogEntry
	2,  // 10: Task.TaskInit:output_type -> TaskInitReply
	4,  // 11: Task.TaskFailure:output_type -> TaskFailureReply
	6,  // 12: Task.TaskComplete:output_type -> TaskCompleteReply
	9,  // 13: Task.TaskLog:output_type -> LogSummary
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_core_pb_cowait_proto_init() }
func file_core_pb_cowait_proto_init() {
	if File_core_pb_cowait_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_pb_cowait_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_pb_cowait_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_pb_cowait_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInitReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_pb_cowait_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskFailureReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_pb_cowait_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskFailureReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_pb_cowait_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskCompleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_pb_cowait_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskCompleteReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_pb_cowait_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_pb_cowait_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_pb_cowait_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_pb_cowait_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_pb_cowait_proto_goTypes,
		DependencyIndexes: file_core_pb_cowait_proto_depIdxs,
		MessageInfos:      file_core_pb_cowait_proto_msgTypes,
	}.Build()
	File_core_pb_cowait_proto = out.File
	file_core_pb_cowait_proto_rawDesc = nil
	file_core_pb_cowait_proto_goTypes = nil
	file_core_pb_cowait_proto_depIdxs = nil
}
