apiVersion: v1
kind: Pod
metadata:
  name: cloud
  labels:
    app: cloud
spec:
  containers:
  - name: cloud
    image: cowait/cloud
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 1338
---
apiVersion: v1
kind: Service
metadata:
  name: cloud
spec:
  type: NodePort
  selector:
    app: cloud
  ports:
  - port: 1338
    targetPort: 1338
